dist: trusty
language: python
python:
  - '2.7'
before_install:
  - sudo apt-get install -qq python-numpy python-scipy
  - npm install -g dredd@stable --no-optional
install:
  - pip install -r requirements.txt
  - pip install -r conda-requirements.txt
script: py.test glassbrain && gunicorn glassbrain:app && dredd
