language: python
python:
  - "2.7"
# install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install -r conda-requirements.txt
# run tests
script: python -m unittest 